uploads = []
outputs = []

[[generated]]
id = "hIte3dWRgnVnp5xhY5TTJ"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/Cell_Rebel.png"
type = "image"
title = "generated_image"

[[generated]]
id = "-LYRL5t_SNVAOIZ2AuHew"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/Cell_Revolutionary.png"
type = "image"
title = "generated_image"

[[generated]]
id = "TpAMtRtpa1I20dqgIUYu8"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/Cell_Wayfinder.png"
type = "image"
title = "generated_image"

[[generated]]
id = "WyeQMlBz7TLmkA_TYzJS7"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/Cell_Barbarian.png"
type = "image"
title = "generated_image"

[[generated]]
id = "2ba9AC-l-ZAYamEP-yhN9"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/Cell_Spy.png"
type = "image"
title = "generated_image"

[[generated]]
id = "JrPwULw0WQCgs4obM-Yh4"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/Cell_Soldier.png"
type = "image"
title = "generated_image"

[[generated]]
id = "3Qs5rwk_WAoq9m0PWRgoV"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/Cell_Conquistador.png"
type = "image"
title = "generated_image"

[[generated]]
id = "QGxVCyWLyPHgAYjAJkgck"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/Cell_Follower.png"
type = "image"
title = "generated_image"

[[generated]]
id = "VQx3Cd3HqqENVvOgJo_1u"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/Cell_Zealot.png"
type = "image"
title = "generated_image"

[[generated]]
id = "dRKJrFwx-0bc3SB1tzknb"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/Cell_PlagueRat.png"
type = "image"
title = "generated_image"

[[generated]]
id = "h86ob3Sd_CZA7CyuWHyT_"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/tmp_Basic.png"
type = "image"
title = "basic cell"

[[generated]]
id = "Y-ms4QqF1yj3Cp8a4oMGT"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/tmp_Immortal.png"
type = "image"
title = "immortal cell"

[[generated]]
id = "p70BeqGuBV3rh_WHnSNcj"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/tmp_Diseased.png"
type = "image"
title = "diseased cell"

[[generated]]
id = "-BhCWTvpeifxIkJue-yZH"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/tmp_Plague.png"
type = "image"
title = "plague cell"

[[generated]]
id = "srCGOWSH6LgI9bJ1CuPSC"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/tmp_Traveler.png"
type = "image"
title = "traveler cell"

[[generated]]
id = "R6JQmMOXSX-Hw4ux4FTM0"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/tmp_Explorer.png"
type = "image"
title = "explorer cell"

[[generated]]
id = "RuPVLogR0uwcMBzyvPiAW"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/tmp_Doctor.png"
type = "image"
title = "doctor cell"

[[generated]]
id = "KOU8dEExdTrPidaz5kDJS"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/tmp_Warrior.png"
type = "image"
title = "warrior cell"

[[generated]]
id = "3tY272xFFbRQscO3-xIN1"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/tmp_Hunter.png"
type = "image"
title = "hunter cell"

[[generated]]
id = "9UdoL1nc7ZlA1SHEODgov"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/tmp_Bomber.png"
type = "image"
title = "bomber cell"

[[generated]]
id = "Kk6JNk_EOcrHVHZvTKGmu"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/tmp_Conquistador.png"
type = "image"
title = "conquistador cell"

[[generated]]
id = "CFzwv-V7QCzEVJWg7Evmd"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/tmp_Diplomat.png"
type = "image"
title = "diplomat cell"

[[generated]]
id = "9rtMP0UcYRkKLjwLudHqx"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/tmp_King.png"
type = "image"
title = "king cell"

[[generated]]
id = "EFlciSnS5Shg4R10DfKZg"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/tmp_Voyager.png"
type = "image"
title = "voyager cell"

[[generated]]
id = "0UzJK9uoNJa132UF7Fn83"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/tmp_Islander.png"
type = "image"
title = "islander cell"

[[generated]]
id = "mOkO7OBYwm-5sYtqtc6vv"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/tmp_Savior.png"
type = "image"
title = "savior cell"

[[generated]]
id = "6JYsYmxZ6qi6FjSkDyDX-"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/tmp_Irradiated.png"
type = "image"
title = "irradiated cell"

[[generated]]
id = "CiyDqQrCP4xM1gW2p9IKO"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/tmp_Zombie.png"
type = "image"
title = "zombie cell"

[[generated]]
id = "S3Hv0_FoY1E3M4OuenZ-p"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/tmp_Necromancer.png"
type = "image"
title = "necromancer cell"

[[generated]]
id = "9ijfHrYqwdEpwh4M-XkYj"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/tmp_Spy.png"
type = "image"
title = "spy cell"

[[generated]]
id = "k6QBF6VeBpDs9RS8uBPAl"
uri = "file://ConwaysWorld.Blazor/wwwroot/Assets/Sprites/tmp_PlagueRat.png"
type = "image"
title = "plague rat cell"
